/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import static java.awt.Color.*;

/**
 *
 * @author blz
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    public Consultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                Base = new javax.swing.JPanel();
                Apresentacao = new RoundedPanel(10, lightGray);
                jLabel1 = new javax.swing.JLabel();
                lblAgendar = new RoundedPanel(10, lightGray);
                btnAgendar = new javax.swing.JButton();
                lblVisualizar = new RoundedPanel(10, lightGray);
                btnVisualizar = new javax.swing.JButton();
                lblReagendar = new RoundedPanel(10, lightGray);
                btnReagendar = new javax.swing.JButton();
                lblDesmarcar = new RoundedPanel(10, lightGray);
                btnDesmarcar = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(153, 255, 153));
                setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                setResizable(false);

                Base.setBackground(new java.awt.Color(0, 194, 203));

                Apresentacao.setPreferredSize(new java.awt.Dimension(245, 165));

                jLabel1.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
                jLabel1.setText("<html><p style=\"text-align:center\">Bem vindo(a) a tela de consultas, nesta tela você pode agendar consultas, visualizar agendamentos, remarcar consultas e realizar cancelamento de agendamentos.</p></html>");

                javax.swing.GroupLayout ApresentacaoLayout = new javax.swing.GroupLayout(Apresentacao);
                Apresentacao.setLayout(ApresentacaoLayout);
                ApresentacaoLayout.setHorizontalGroup(
                        ApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ApresentacaoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addContainerGap())
                );
                ApresentacaoLayout.setVerticalGroup(
                        ApresentacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ApresentacaoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                btnAgendar.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
                btnAgendar.setText("Agendar consulta");
                btnAgendar.setBorder(null);
                btnAgendar.setBorderPainted(false);
                btnAgendar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAgendarActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout lblAgendarLayout = new javax.swing.GroupLayout(lblAgendar);
                lblAgendar.setLayout(lblAgendarLayout);
                lblAgendarLayout.setHorizontalGroup(
                        lblAgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAgendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                lblAgendarLayout.setVerticalGroup(
                        lblAgendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAgendar, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                );

                btnVisualizar.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
                btnVisualizar.setText("Visualizar agendamento");

                javax.swing.GroupLayout lblVisualizarLayout = new javax.swing.GroupLayout(lblVisualizar);
                lblVisualizar.setLayout(lblVisualizarLayout);
                lblVisualizarLayout.setHorizontalGroup(
                        lblVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                );
                lblVisualizarLayout.setVerticalGroup(
                        lblVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                );

                lblReagendar.setPreferredSize(new java.awt.Dimension(245, 75));

                btnReagendar.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
                btnReagendar.setText("Reagendar consulta");

                javax.swing.GroupLayout lblReagendarLayout = new javax.swing.GroupLayout(lblReagendar);
                lblReagendar.setLayout(lblReagendarLayout);
                lblReagendarLayout.setHorizontalGroup(
                        lblReagendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnReagendar, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                );
                lblReagendarLayout.setVerticalGroup(
                        lblReagendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnReagendar, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                );

                lblDesmarcar.setPreferredSize(new java.awt.Dimension(245, 75));

                btnDesmarcar.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
                btnDesmarcar.setText("Desmarcar consulta");

                javax.swing.GroupLayout lblDesmarcarLayout = new javax.swing.GroupLayout(lblDesmarcar);
                lblDesmarcar.setLayout(lblDesmarcarLayout);
                lblDesmarcarLayout.setHorizontalGroup(
                        lblDesmarcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnDesmarcar, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                );
                lblDesmarcarLayout.setVerticalGroup(
                        lblDesmarcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnDesmarcar, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout BaseLayout = new javax.swing.GroupLayout(Base);
                Base.setLayout(BaseLayout);
                BaseLayout.setHorizontalGroup(
                        BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BaseLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDesmarcar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblReagendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(lblVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Apresentacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblAgendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(60, Short.MAX_VALUE))
                );
                BaseLayout.setVerticalGroup(
                        BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BaseLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(Apresentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                                .addComponent(lblAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblReagendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDesmarcar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        // TODO add your handling code here:
        Agendar agendaTela = new Agendar();
        this.dispose();
        agendaTela.setVisible(true);
    }//GEN-LAST:event_btnAgendarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel Apresentacao;
        private javax.swing.JPanel Base;
        private javax.swing.JButton btnAgendar;
        private javax.swing.JButton btnDesmarcar;
        private javax.swing.JButton btnReagendar;
        private javax.swing.JButton btnVisualizar;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel lblAgendar;
        private javax.swing.JPanel lblDesmarcar;
        private javax.swing.JPanel lblReagendar;
        private javax.swing.JPanel lblVisualizar;
        // End of variables declaration//GEN-END:variables
}
