/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DTO.PacienteDTO;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author mathe
 */
public class LoginTELA extends javax.swing.JFrame {

    /**
     * Creates new form LoginTELA
     */
    public LoginTELA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Base = new javax.swing.JPanel();
        tfCns = new javax.swing.JTextField();
        tfCpf = new javax.swing.JTextField();
        botaoEntrar = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(360, 800));
        setResizable(false);

        Base.setBackground(new java.awt.Color(0, 194, 203));

        tfCns.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfCns.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCns.setText("CNS");
        tfCns.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCnsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCnsFocusLost(evt);
            }
        });
        tfCns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCnsActionPerformed(evt);
            }
        });
        tfCns.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCnsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCnsKeyTyped(evt);
            }
        });

        tfCpf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tfCpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCpf.setText("CPF");
        tfCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCpfFocusLost(evt);
            }
        });
        tfCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCpfActionPerformed(evt);
            }
        });
        tfCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCpfKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCpfKeyTyped(evt);
            }
        });

        botaoEntrar.setBackground(new java.awt.Color(255, 255, 255));
        botaoEntrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botaoEntrar.setText("Entrar");
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/logo/CONSULTEI_2.png"))); // NOI18N

        javax.swing.GroupLayout BaseLayout = new javax.swing.GroupLayout(Base);
        Base.setLayout(BaseLayout);
        BaseLayout.setHorizontalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfCns)
            .addComponent(tfCpf, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(botaoEntrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logo)
                .addGap(159, 159, 159))
            .addGroup(BaseLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(logo)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        BaseLayout.setVerticalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BaseLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfCns, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Base, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfCnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCnsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfCnsActionPerformed

    private void tfCnsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCnsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCnsKeyPressed

    private void tfCnsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCnsKeyTyped

        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (tfCns.getText().length() >= 15) {
            evt.consume();
        }

    }//GEN-LAST:event_tfCnsKeyTyped

    private void tfCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCpfActionPerformed

    }//GEN-LAST:event_tfCpfActionPerformed

    private void tfCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCpfKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCpfKeyPressed

    private void tfCpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCpfKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
        if (tfCpf.getText().length() >= 11) {
            evt.consume();
        }
    }//GEN-LAST:event_tfCpfKeyTyped

    private void tfCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCpfFocusGained
        if (tfCpf.getText().equals("CPF")) {
            tfCpf.setText("");
        }
    }//GEN-LAST:event_tfCpfFocusGained

    private void tfCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCpfFocusLost
        if (tfCpf.getText().equals("")) {
            tfCpf.setText("CPF");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCpfFocusLost

    private void tfCnsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCnsFocusGained
        // TODO add your handling code here:
        if (tfCns.getText().equals("CNS")) {
            tfCns.setText("");
        }
    }//GEN-LAST:event_tfCnsFocusGained

    private void tfCnsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCnsFocusLost
        // TODO add your handling code here:
        if (tfCns.getText().equals("")) {
            tfCns.setText("CNS");
        }
    }//GEN-LAST:event_tfCnsFocusLost

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
        String cns, cpf;
        cns = tfCns.getText();
        cpf = tfCpf.getText();

        PacienteDTO objpacientedto = new PacienteDTO();

        objpacientedto.setCns(cns);
        objpacientedto.setCpf(cpf);

        if (objpacientedto.autenticaPaciente()) {
            try {
                Home homeTela = new Home();
                this.dispose();
                homeTela.setVisible(true);
            } catch (Exception e) {
                Home homeTela = new Home();
                this.dispose();
                homeTela.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(null,"Dados Incorretos", "Erro", 0);
        }
    }//GEN-LAST:event_botaoEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginTELA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginTELA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginTELA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginTELA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginTELA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField tfCns;
    private javax.swing.JTextField tfCpf;
    // End of variables declaration//GEN-END:variables
}
